name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag garretth2007/zphisher:latest
    - name: Push the Docker image
      run: docker login -u garretth2007 -p ${{ secrets.DOCKER_TOKEN }} && docker push garretth2007/zphisher:late
